# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBMParking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'RealmSwift'
  pod 'Firebase/Database'
  pod 'AlamofireImage', '~> 4.1'
  # Pods for NIBMParking

end
